// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/energy-consumption-rate": {
            "get": {
                "description": "The Building exposes the metrics of electrical energy consumption (server+cooling) related to the entire Building in kW",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "The Building exposes the metrics of electrical energy consumption (server+cooling) related to the entire Building in kW",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.EnergyConsumptionRateResponse"
                        }
                    }
                }
            }
        },
        "/future-energy-consumption-rate": {
            "get": {
                "description": "Accepts a possible energy range for the optimisation, e.g.: \"10-25kW\". Returns a value in kW contained in the range representing",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "A possible range for the optimisation, e.g.: \"10-25kW\" for the Building",
                "parameters": [
                    {
                        "description": "Request providing a possible range of energy consumption",
                        "name": "energy-consumption-rate-request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.FutureEnergyConsumptionRateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.FutureEnergyConsumptionRateResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.EnergyConsumptionRateResponse": {
            "type": "object",
            "properties": {
                "consumed": {
                    "type": "integer"
                }
            }
        },
        "main.FutureEnergyConsumptionRateRequest": {
            "type": "object",
            "properties": {
                "max": {
                    "type": "integer"
                },
                "min": {
                    "type": "integer"
                },
                "time": {
                    "type": "string"
                }
            }
        },
        "main.FutureEnergyConsumptionRateResponse": {
            "type": "object",
            "properties": {
                "min": {
                    "type": "integer"
                },
                "time": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
